export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-8 pt-20">
      <h1 className="mb-6 text-center text-4xl font-bold">Privacy Policy</h1>
      <p className="mb-4">Last updated: November 10, 2022</p>
      <p className="mb-6">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You. We use Your Personal data to provide and improve the Service. By
        using the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Interpretation and Definitions
        </h2>
        <h3 className="mb-2 text-xl font-semibold">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h3 className="mb-2 text-xl font-semibold">Definitions</h3>
        <ul className="mb-4 list-disc space-y-2 pl-5">
          <li>
            <strong>Account:</strong> A unique account created for You to access
            our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate:</strong> An entity that controls, is controlled
            by or is under common control with a party, where
            &quot;control&quot; means ownership of 50% or more of the shares,
            equity interest or other securities entitled to vote for election of
            directors or other managing authority.
          </li>
          <li>
            <strong>Application:</strong> The software program provided by the
            Company downloaded by You on any electronic device, named Live
            Timeless.
          </li>
          <li>
            <strong>Company:</strong> Refers to Live Timeless, 700 4 Ave SW,
            Calgary, Alberta CA.
          </li>
          <li>
            <strong>Country:</strong> Refers to Alberta, Canada.
          </li>
          <li>
            <strong>Device:</strong> Any device that can access the Service such
            as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data:</strong> Any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service:</strong> Refers to the Application.
          </li>
          <li>
            <strong>Service Provider:</strong> Any natural or legal person who
            processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Third-party Social Media Service:</strong> Any website or
            any social network website through which a User can log in or create
            an account to use the Service.
          </li>
          <li>
            <strong>Usage Data:</strong> Data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>You:</strong> The individual accessing or using the Service,
            or the company, or other legal entity on behalf of which such
            individual is accessing or using the Service, as applicable.
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Collecting and Using Your Personal Data
        </h2>
        <h3 className="mb-2 text-xl font-semibold">Types of Data Collected</h3>
        <h4 className="mb-2 text-lg font-medium">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="mb-4 list-disc pl-5">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>
        <h4 className="mb-2 text-lg font-medium">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service. It may
          include information such as Your Device&apos;s Internet Protocol
          address, browser type, browser version, pages visited, time and date
          of visits, time spent on pages, unique device identifiers, and other
          diagnostic data.
        </p>
        <h4 className="mb-2 text-lg font-medium">
          Information from Third-Party Social Media Services
        </h4>
        <p className="mb-4">
          The Company allows You to create an account and log in to use the
          Service through Third-party Social Media Services such as Google,
          Facebook, Twitter, and LinkedIn. If You choose to register through or
          grant us access to a Third-Party Social Media Service, We may collect
          Personal data associated with Your Third-Party Social Media
          Service&apos;s account.
        </p>
        <h4 className="mb-2 text-lg font-medium">
          Information Collected while Using the Application
        </h4>
        <p className="mb-4">
          While using Our Application, We may collect, with Your prior
          permission:
        </p>
        <ul className="mb-4 list-disc pl-5">
          <li>
            Information from your Device&apos;s phone book (contacts list)
          </li>
          <li>
            Pictures and other information from your Device&apos;s camera and
            photo library
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Use of Your Personal Data
        </h2>
        <p className="mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>To provide and maintain our Service</li>
          <li>To manage Your Account</li>
          <li>For the performance of a contract</li>
          <li>To contact You</li>
          <li>
            To provide You with news, special offers and general information
          </li>
          <li>To manage Your requests</li>
          <li>For business transfers</li>
          <li>
            For other purposes such as data analysis, identifying usage trends,
            and improving our Service
          </li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Sharing of Your Personal Data
        </h2>
        <p className="mb-4">
          We may share Your personal information in the following situations:
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>With Service Providers</li>
          <li>For business transfers</li>
          <li>With Affiliates</li>
          <li>With business partners</li>
          <li>With other users</li>
          <li>With Your consent</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Retention of Your Personal Data
        </h2>
        <p>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. We will
          retain and use Your Personal Data to the extent necessary to comply
          with our legal obligations, resolve disputes, and enforce our legal
          agreements and policies.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Transfer of Your Personal Data
        </h2>
        <p>
          Your information, including Personal Data, is processed at the
          Company&apos;s operating offices and in any other places where the
          parties involved in the processing are located. Your consent to this
          Privacy Policy followed by Your submission of such information
          represents Your agreement to that transfer.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Delete Your Personal Data
        </h2>
        <p>
          You have the right to delete or request that We assist in deleting the
          Personal Data that We have collected about You. Our Service may give
          You the ability to delete certain information about You from within
          the Service. You may update, amend, or delete Your information at any
          time by signing in to Your Account and visiting the account settings
          section.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Disclosure of Your Personal Data
        </h2>
        <h3 className="mb-2 text-xl font-semibold">Business Transactions</h3>
        <p className="mb-4">
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred.
        </p>
        <h3 className="mb-2 text-xl font-semibold">Law enforcement</h3>
        <p className="mb-4">
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities.
        </p>
        <h3 className="mb-2 text-xl font-semibold">Other legal requirements</h3>
        <p>
          The Company may disclose Your Personal Data in the good faith belief
          that such action is necessary to comply with a legal obligation,
          protect and defend the rights or property of the Company, prevent or
          investigate possible wrongdoing, protect the personal safety of Users
          or the public, or protect against legal liability.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Security of Your Personal Data
        </h2>
        <p>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">Children&apos;s Privacy</h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent or guardian and You are aware
          that Your child has provided Us with Personal Data, please contact Us.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">Links to Other Websites</h2>
        <p>
          Our Service may contain links to other websites that are not operated
          by Us. If You click on a third party link, You will be directed to
          that third party&apos;s site. We strongly advise You to review the
          Privacy Policy of every site You visit.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">
          Changes to this Privacy Policy
        </h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page and
          updating the &quot;Last updated&quot; date at the top of this Privacy
          Policy.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="mb-4 text-2xl font-semibold">Contact Us</h2>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul className="list-disc space-y-2 pl-5">
          <li>By email: info@livetimeless.com</li>
          <li>
            By visiting this page on our website:{" "}
            <a
              href="https://www.livetimeless.com"
              className="text-blue-600 hover:underline"
            >
              https://www.livetimeless.com
            </a>
          </li>
        </ul>
      </section>
    </div>
  );
}
